version: '3'
services:
  redis:
    image: redis:alpine
    command: ['redis-server', '--appendonly', 'yes']
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
  web:
    build: .
    ports:
      - '5000:5000'
    networks:
      - redis-net
    depends_on:
      - redis
networks:
  redis-net:
volumes:
  redis-data:
